language: java
jdk: openjdk8

branches:
  only:
    - master
    - develop

script:
  - mvn install -N
  - mvn clean test
  - mvn package

notifications:
  email:
    on_success: never
    on_failure: always